""""not in use, decided to allow cointegration tests to find pairs"""

SECTOR_MAPPING = {
    "AI": ['0G', 'A2Z', 'ACT', 'AI', 'AIXBT', 'ARKM', 'BARD', 'BIO', 'COOKIE', 'CYBER', 'FET', 'GIGGLE', 'GRT', 'HUMA', 'IO', 'JASMY', 'KAITO', 'MIRA', 'NEAR', 'NFP', 'NMR', 'OPEN', 'PARTI', 'RENDER', 'SAHARA', 'SAPIEN', 'SHELL', 'SOMI', 'SOPH', 'SXT', 'TAO', 'TURBO', 'VANA', 'VIRTUAL', 'WLD'],
    "BTC Ecosystem": ['1000SATS', 'BB', 'HEMI', 'ORDI', 'STX', 'WBTC'],
    "Bridge": ['ACX', 'CELR', 'STG', 'SYN', 'W'],
    "Cloud Computing": ['FLUX', 'GLM', 'RLC'],
    "Cross-chain": ['ACX', 'ATOM', 'AXL', 'BTTC', 'CELR', 'DOT', 'ICX', 'PORTAL', 'QNT', 'RUNE', 'STG', 'SYN', 'W', 'WAN', 'ZRO'],
    "DEX": ['BANANA', 'BNT', 'CAKE', 'CETUS', 'CRV', 'DODO', 'DYDX', 'GMX', 'IDEX', 'JOE', 'KNC', 'MAV', 'ORCA', 'OSMO', 'QUICK', 'RAY', 'RUNE', 'SUSHI', 'UNI', 'WOO', 'ZRX'],
    "DEX Aggregator": ['1INCH', 'BEL', 'COW', 'JUP'],
    "Data": ['ARKM', 'COOKIE', 'DIA', 'GRT', 'GUN', 'JASMY', 'MDT', 'NMR', 'PROM', 'SAHARA', 'SXT', 'VANA'],
    "Data Availability": ['0G', 'ALT', 'TIA'],
    "DeFi": ['1INCH', 'AAVE', 'ACX', 'AEVO', 'AIXBT', 'ALCX', 'ALLO', 'ASTER', 'AVA', 'BANANA', 'BB', 'BEL', 'BERA', 'BICO', 'BIO', 'BMT', 'BNT', 'C', 'C98', 'CAKE', 'CETUS', 'COMP', 'COTI', 'COW', 'CRV', 'CVX', 'DEGO', 'DEXE', 'DODO', 'DOLO', 'DYDX', 'EIGEN', 'ENA', 'ENSO', 'ETHFI', 'F', 'FARM', 'FET', 'FF', 'FIDA', 'FORM', 'FORTH', 'G', 'GMX', 'GNS', 'HFT', 'HIGH', 'HUMA', 'HYPER', 'IDEX', 'ILV', 'INIT', 'INJ', 'JOE', 'JST', 'JTO', 'JUP', 'KAVA', 'KERNEL', 'KMNO', 'KNC', 'LDO', 'LISTA', 'LQTY', 'LRC', 'MAV', 'MITO', 'MLN', 'MORPHO', 'NOM', 'NTRN', 'OGN', 'OM', 'ONDO', 'ORCA', 'OSMO', 'PENDLE', 'PUMP', 'PYTH', 'QI', 'QUICK', 'RAD', 'RAY', 'RDNT', 'RESOLV', 'REZ', 'RPL', 'RSR', 'RUNE', 'SHIB', 'SNX', 'SOLV', 'SPELL', 'SSV', 'STG', 'SUN', 'SUSHI', 'SXP', 'SYN', 'SYRUP', 'THE', 'TKO', 'TNSR', 'TRU', 'UMA', 'UNI', 'USUAL', 'W', 'WBTC', 'WIN', 'WLFI', 'WOO', 'XVS', 'YB', 'YFI', 'ZRX'],
    "DePIN": ['ANKR', 'DENT', 'GPS', 'IO', 'LPT', 'OPEN', 'POND', 'POWR', 'RENDER', 'SHELL', 'SPK'],
    "Derivatives": ['AEVO', 'DYDX', 'GMX', 'GNS', 'SNX', 'UMA'],
    "Exchange Token": ['BNB', 'FTT', 'TKO'],
    "Fan Token": ['ACM', 'ALPINE', 'ASR', 'ATM', 'BAR', 'CHZ', 'CITY', 'JUV', 'LAZIO', 'OG', 'PORTO', 'PSG', 'SANTOS'],
    "Gaming": ['2Z', 'ACE', 'AGLD', 'ALICE', 'APE', 'AXS', 'BEAMX', 'CATI', 'CHR', 'ENJ', 'EPIC', 'ERA', 'FF', 'FUN', 'GALA', 'GMT', 'HIGH', 'HMSTR', 'HOOK', 'ILV', 'IMX', 'MAGIC', 'MANA', 'MBOX', 'MMT', 'NEWT', 'NFP', 'NOT', 'NXPC', 'OG', 'PIXEL', 'PORTAL', 'PYR', 'RONIN', 'SAND', 'SLP', 'SOMI', 'SUPER', 'TLM', 'VANRY', 'VIRTUAL', 'WAXP', 'WIN', 'XAI', 'YGG'],
    "Identity": ['CVC', 'ENS', 'ID', 'WLD'],
    "Infrastructure": ['0G', 'A', 'ACH', 'ADX', 'ALT', 'AMP', 'ANKR', 'AR', 'ARPA', 'ATA', 'AUDIO', 'AVNT', 'AXL', 'BAT', 'BICO', 'CELR', 'COS', 'CTK', 'CTSI', 'CVC', 'DENT', 'DYM', 'EDEN', 'ENS', 'FLUX', 'GLM', 'GRT', 'GTC', 'GUN', 'HIVE', 'HOLO', 'HOT', 'ID', 'IOST', 'IOTX', 'LAYER', 'LINK', 'LPT', 'MASK', 'MBL', 'MDT', 'MET', 'NIL', 'OGN', 'OXT', 'PHA', 'PHB', 'POLYX', 'POND', 'POWR', 'PROM', 'PROVE', 'PUNDIX', 'QNT', 'RAD', 'REQ', 'RIF', 'RLC', 'SFP', 'SIGN', 'SPK', 'SSV', 'STORJ', 'T', 'TFUEL', 'THETA', 'TUT', 'TWT', 'WCT', 'ZBT', 'ZRO'],
    "IoT": ['IOTA', 'IOTX', 'JASMY', 'VET', 'VTHO'],
    "L1": ['ADA', 'ALGO', 'APT', 'ARK', 'ASTR', 'ATOM', 'AVAX', 'BCH', 'BERA', 'BNB', 'BTC', 'BTTC', 'CELO', 'CFX', 'CKB', 'DASH', 'DCR', 'DGB', 'DOT', 'EGLD', 'ETC', 'ETH', 'FIL', 'FLOW', 'GAS', 'GLMR', 'HBAR', 'HYPER', 'ICP', 'ICX', 'INJ', 'IOTA', 'KAIA', 'KAVA', 'KSM', 'LSK', 'LTC', 'LUNA', 'LUNC', 'MINA', 'MOVE', 'MOVR', 'NEAR', 'NEO', 'OM', 'ONE', 'ONT', 'PIVX', 'PLUME', 'QTUM', 'RONIN', 'ROSE', 'RVN', 'S', 'SAGA', 'SC', 'SEI', 'SOL', 'STRAX', 'STX', 'SUI', 'SYS', 'TAO', 'TIA', 'TON', 'TRX', 'VANRY', 'VET', 'VIC', 'VTHO', 'WAN', 'XEC', 'XLM', 'XPL', 'XRP', 'XTZ', 'XVG', 'ZEC', 'ZEN', 'ZIL'],
    "L2": ['ARB', 'CTSI', 'DUSK', 'HEMI', 'IMX', 'LINEA', 'LRC', 'MANTA', 'OP', 'POL', 'SCR', 'SKL', 'STRK', 'XAI', 'ZK', 'ZKC'],
    "Lending": ['AAVE', 'ALCX', 'COMP', 'LQTY', 'MORPHO', 'NEXO', 'RDNT', 'SPELL', 'TRU', 'XVS'],
    "Liquid Staking": ['ETHFI', 'JTO', 'LDO', 'LISTA', 'RPL', 'SSV', 'THE'],
    "Marketplace": ['AUCTION', 'BLUR', 'ME', 'RARE'],
    "Meme": ['1000CAT', '1000CHEEMS', '1000SATS', '1MBABYDOGE', 'ACT', 'BABY', 'BANANAS31', 'BOME', 'BONK', 'BROCCOLI714', 'CATI', 'DOGE', 'DOGS', 'FLOKI', 'GIGGLE', 'HMSTR', 'KITE', 'MEME', 'MUBARAK', 'NEIRO', 'NOT', 'PENGU', 'PEOPLE', 'PEPE', 'PNUT', 'PUMP', 'RED', 'SHIB', 'TREE', 'TRUMP', 'TST', 'TURBO', 'TURTLE', 'WIF'],
    "Metaverse": ['ALICE', 'MANA', 'MBOX', 'SAND'],
    "Modular": ['DYM', 'INIT', 'SAGA', 'TIA'],
    "NFT": ['AGLD', 'ANIME', 'APE', 'AUCTION', 'AXS', 'BLUR', 'DEGO', 'ENJ', 'FLOW', 'GALA', 'IMX', 'MAGIC', 'ME', 'ORDI', 'PENGU', 'PYR', 'RARE', 'RVN', 'WAXP'],
    "Oracle": ['API3', 'BAND', 'DIA', 'LINK', 'PYTH', 'TRB', 'UMA'],
    "Payments": ['ACH', 'AMP', 'BCH', 'CELO', 'COTI', 'DASH', 'LTC', 'MTL', 'PUNDIX', 'REQ', 'SXP', 'UTK', 'XEC', 'XLM', 'XRP'],
    "Privacy": ['ARPA', 'ATA', 'DASH', 'DCR', 'DUSK', 'MINA', 'OXT', 'PHA', 'PIVX', 'ROSE', 'T', 'XVG', 'ZEC', 'ZEN'],
    "RWA": ['AT', 'HUMA', 'OM', 'ONDO', 'PAXG', 'PLUME', 'POLYX', 'STO', 'USUAL', 'WLFI'],
    "Restaking": ['EIGEN', 'ETHFI', 'KERNEL', 'REZ'],
    "Smart Contract Platform": ['ADA', 'ALGO', 'APT', 'ARB', 'ASTR', 'AVAX', 'BERA', 'BNB', 'CELO', 'CFX', 'CHR', 'CKB', 'DUSK', 'EGLD', 'ETH', 'FLOW', 'GLMR', 'HBAR', 'ICP', 'INJ', 'KAIA', 'KAVA', 'KSM', 'LSK', 'LUNA', 'LUNC', 'MANTA', 'MOVE', 'MOVR', 'NEAR', 'NEO', 'NTRN', 'ONE', 'ONT', 'OP', 'POL', 'QTUM', 'RIF', 'ROSE', 'S', 'SEI', 'SKL', 'SOL', 'STRAX', 'STRK', 'STX', 'SUI', 'SYS', 'TON', 'TRX', 'VIC', 'XTZ', 'ZIL', 'ZK'],
    "Social": ['AUDIO', 'AWE', 'COS', 'CYBER', 'DEXE', 'EDU', 'GTC', 'HIVE', 'KAITO', 'MASK', 'PARTI', 'PEOPLE', 'RED', 'SAPIEN', 'STEEM', 'TON', 'TOWNS'],
    "Stablecoin": ['AEUR', 'BFUSD', 'ENA', 'EUR', 'EURI', 'FDUSD', 'JST', 'PAXG', 'RESOLV', 'RSR', 'TUSD', 'USD1', 'USDC', 'USDE', 'USDP', 'USTC', 'USUAL', 'XUSD'],
    "Storage": ['AR', 'FIL', 'SC', 'STORJ'],
    "Wallet": ['C98', 'SFP', 'TWT'],
    "Yield": ['CVX', 'FARM', 'PENDLE', 'QI', 'SOLV', 'SYRUP', 'YB', 'YFI'],
    "ZK": ['LINEA', 'MANTA', 'MINA', 'NIL', 'PROVE', 'SCR', 'SIGN', 'STRK', 'ZK', 'ZKC'],
}